import { Kategori, Link, Mitra, pelanggan } from "@/types";

export const Produks: Kategori[] = [
  {
    nama: "Konstruksi",
    slug: "konstruksi",
    subKategori: [
      {
        nama: "Design & Konstruksi Indoor",
        slug: "design-&-konstruksi-indoor",
        deskripsi: null,
        cover: "/produk/konstruksi/construction1.png",
        gambar: [
          "/produk/konstruksi/designIndoor/DesignIndoor1.png",
          "/produk/konstruksi/designIndoor/DesignIndoor2.png",
          "/produk/konstruksi/designIndoor/DesignIndoor3.png",
        ],
        produk: [],
      },
      {
        nama: "Instalasi",
        slug: "instalasi",
        deskripsi: null,
        cover: "/produk/konstruksi/construction2.png",
        gambar: [
          "/produk/konstruksi/instalasi/Instalasi1.png",
          "/produk/konstruksi/instalasi/Instalasi2.png",
          "/produk/konstruksi/instalasi/Instalasi3.png",
          "/produk/konstruksi/instalasi/Instalasi4.png",
          "/produk/konstruksi/instalasi/Instalasi5.png",
        ],
        produk: [
          {
            nama: "Papan Nama Ruangan",
            slug: "papan-nama-ruangan",
            deskripsi: null,
            cover: "/produk/konstruksi/instalasi/PapanNamaRuangan.png",
            gambar: [],
          },
          {
            nama: "Papan Tanda Arah",
            slug: "papan-tanda-arah",
            deskripsi: null,
            cover: "/produk/konstruksi/instalasi/PapanTandaArah.png",
            gambar: [],
          },
          {
            nama: "Papan Akrilik",
            slug: "papan-akrilik",
            deskripsi: null,
            cover: "/produk/konstruksi/instalasi/PapanAkrilik.png",
            gambar: [],
          },
          {
            nama: "Stiker Sandblast",
            slug: "stiker-sandblast",
            deskripsi: null,
            cover: "/produk/konstruksi/instalasi/StikerSanblas.png",
            gambar: [],
          },
        ],
      },
    ],
  },
  {
    nama: "Percetakan",
    slug: "percetakan",
    subKategori: [
      {
        nama: "Souvenir & Konveksi",
        slug: "souvenir-&-konveksi",
        deskripsi: null,
        cover: "/produk/percetakan/printing1.png",
        gambar: [
          "/produk/percetakan/souvenir/SouvenirKonveksi1.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi2.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi3.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi4.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi5.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi6.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi7.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi8.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi9.png",
          "/produk/percetakan/souvenir/SouvenirKonveksi10.png",
        ],
        produk: [
          {
            nama: "Kaos Custom",
            slug: "kaos-custom",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct1.png",
            gambar: [],
          },
          {
            nama: "Topi",
            slug: "topi",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct2.png",
            gambar: [],
          },
          {
            nama: "Gantungan Label",
            slug: "gantungan-label",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct3.png",
            gambar: [],
          },
          {
            nama: "Botol Minum",
            slug: "botol-minum",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct4.png",
            gambar: [],
          },
          {
            nama: "Payung",
            slug: "payung",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct5.png",
            gambar: [],
          },
          {
            nama: "Gantungan Kunci",
            slug: "gantungan-kunci",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct6.png",
            gambar: [],
          },
          {
            nama: "Totebag",
            slug: "totebag",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct7.png",
            gambar: [],
          },
          {
            nama: "Handuk Custom",
            slug: "handuk-custom",
            deskripsi: null,
            cover: "/produk/percetakan/souvenir/SouvenirKonveksiProduct8.png",
            gambar: [],
          },
        ],
      },
      {
        nama: "Promosi",
        slug: "promosi",
        deskripsi: null,
        cover: "/produk/percetakan/printing2.png",
        gambar: [
          "/produk/percetakan/promosi/Promosi1.png",
          "/produk/percetakan/promosi/Promosi2.png",
        ],
        produk: [
          {
            nama: "Flyer",
            slug: "flyer",
            deskripsi: null,
            cover: "/produk/percetakan/promosi/PromosiProduct1.png",
            gambar: [],
          },
          {
            nama: "Booklet",
            slug: "booklet",
            deskripsi: null,
            cover: "/produk/percetakan/promosi/PromosiProduct2.png",
            gambar: [],
          },
          {
            nama: "Banner",
            slug: "banner",
            deskripsi: null,
            cover: "/produk/percetakan/promosi/PromosiProduct3.png",
            gambar: [],
          },
        ],
      },
      {
        nama: "Kemasan",
        slug: "kemasan",
        deskripsi: null,
        cover: "/produk/percetakan/printing3.png",
        gambar: [
          "/produk/percetakan/kemasan/Kemasan1.png",
          "/produk/percetakan/kemasan/Kemasan2.png",
        ],
        produk: [
          {
            nama: "Kotak Produk Bahan Kardus Gelombang",
            slug: "kotak-produk-bahan-kardus-gelombang",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct1.png",
            gambar: [],
          },
          {
            nama: "Kotak Produk Bahan Kertas",
            slug: "kotak-produk-bahan-kertas",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct2.png",
            gambar: [],
          },
          {
            nama: "Kotak Produk Bahan Kertas + Pita Tarik",
            slug: "kotak-produk-bahan-kertas-pita-tarik",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct3.png",
            gambar: [],
          },
          {
            nama: "Paper Bag Bahan Kertas",
            slug: "paper-bag-bahan-kertas",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct4.png",
            gambar: [],
          },
          {
            nama: "Kemasan Botol",
            slug: "kemasan-botol",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct5.png",
            gambar: [],
          },
          {
            nama: "Kotak Hampers",
            slug: "kotak-hampers",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct6.png",
            gambar: [],
          },
          {
            nama: "Sampul",
            slug: "sampul",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct7.png",
            gambar: [],
          },
          {
            nama: "Paper Bag",
            slug: "paper-bag",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct8.png",
            gambar: [],
          },
          {
            nama: "Kotak Gamble + Handle",
            slug: "kotak-gamble-handle",
            deskripsi: null,
            cover: "/produk/percetakan/kemasan/KemasanProduct9.png",
            gambar: [],
          },
        ],
      },
      {
        nama: "Perlengkapan Kantor",
        slug: "perlengkapan-kantor",
        deskripsi: null,
        cover: "/produk/percetakan/printing4.png",
        gambar: [
          "/produk/percetakan/kantor/PerlengkapanKantor1.png",
          "/produk/percetakan/kantor/PerlengkapanKantor2.png",
        ],
        produk: [
          {
            nama: "Buku Agenda",
            slug: "buku-agenda",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct1.png",
            gambar: [],
          },
          {
            nama: "Kartu Ucapan",
            slug: "kartu-ucapan",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct2.png",
            gambar: [],
          },
          {
            nama: "ID Card",
            slug: "id-card",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct3.png",
            gambar: [],
          },
          {
            nama: "Amplop",
            slug: "amplop",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct4.png",
            gambar: [],
          },
          {
            nama: "Angpao",
            slug: "angpao",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct5.png",
            gambar: [],
          },
          {
            nama: "Brosur",
            slug: "brodur",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct6.png",
            gambar: [],
          },
          {
            nama: "Kop Surat",
            slug: "kop-surat",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct7.png",
            gambar: [],
          },
          {
            nama: "Lanyard",
            slug: "lanyard",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct8.png",
            gambar: [],
          },
          {
            nama: "Kartu Nama",
            slug: "kartu-nama",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct9.png",
            gambar: [],
          },
          {
            nama: "Map Folder",
            slug: "map-folder",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct10.png",
            gambar: [],
          },
          {
            nama: "Kartu Member",
            slug: "kartu-member",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct11.png",
            gambar: [],
          },
          {
            nama: "Kalender",
            slug: "kalender",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct12.png",
            gambar: [],
          },
          {
            nama: "Tiket",
            slug: "tiket",
            deskripsi: null,
            cover: "/produk/percetakan/kantor/PerlengkapanKantorProduct13.png",
            gambar: [],
          },
        ],
      },
    ],
  },
];

export const Links: Link[] = [
  {
    label: "Produk Kami",
    url: "/produk",
  },
  {
    label: "Tentang Kami",
    url: "/tentang",
  },
  {
    label: "Kontak Kami",
    url: "/kontak",
  },
];

export const Mitras: Mitra[] = [
  { url: "/images/client-1.png", label: null },
  { url: "/images/client-2.png", label: null },
  { url: "/images/client-3.png", label: null },
  { url: "/images/client-4.png", label: null },
  { url: "/images/client-5.png", label: null },
  { url: "/images/client-6.png", label: null },
  { url: "/images/client-7.png", label: null },
  { url: "/images/client-8.png", label: null },
  { url: "/images/client-9.png", label: null },
  { url: "/images/client-10.png", label: null },
  { url: "/images/client-11.png", label: null },
  { url: "/images/client-12.png", label: null },
  { url: "/images/client-13.png", label: null },
  { url: "/images/client-14.png", label: null },
];

export const Pelanggans: pelanggan[] = [
  {
    nama: "Jhon Doe",
    foto: "/client1.png",
    perusahaan: "CDB",
    tahun: "2024",
    judul: "text",
    deskripsi: "lorem ipsum",
  },
  {
    nama: "Jane Smith",
    foto: "/client1.png",
    perusahaan: "ABC Company",
    tahun: "2023",
    judul: "text",
    deskripsi: "lorem ipsum",
  },
  {
    nama: "Michael Johnson",
    foto: "/client1.png",
    perusahaan: "XYZ Corporation",
    tahun: "2022",
    judul: "text",
    deskripsi: "lorem ipsum",
  },
];
